name: Destroy AWS Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy_infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var="aws_region=${{ secrets.AWS_REGION }}" -var="ssh_key_name=terraform-key" -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" -var="bucket_name=${{ secrets.TF_BUCKET_NAME }}"
